Hajri
Team9-DIN21AWAP/AWAP-front-end pull request #23
Opened 2022-11-22 12:26 UTC by MohHajri

2022-11-22 13:02 UTC, TheZukab approved these changes

2022-11-22 18:57 UTC, Rexol requested changes

2022-11-22 18:57 UTC, Rexol commented on src/components/charts/Vis7.js
> +        // {
Remove commented code before pushing to main

2022-11-22 18:57 UTC, Rexol commented on src/components/charts/Vis7.js
> +// import DATA from './C02.json'
same here

2022-11-22 18:57 UTC, Rexol commented on src/components/charts/Vis7.js
> +        //   {
same here

2022-11-23 13:01 UTC, Rexol approved these changes

2022-11-23 13:04 UTC, merged